---
- hosts: all
  become: yes
  gather_facts: False
  tasks:

  - name: Install EPEL-release
    yum: name=epel-release state=present

  - name: Install java_1.8
    yum: name=java-1.8.0-openjdk.x86_64 state=present

  - name: Install tomcat
    yum: name=tomcat state=present

  - name: Start tomcat service
    service: name=tomcat state=started

  - name: Stop iptables
    service: name=iptables state=stopped
